"""add latest update time

Revision ID: 68a2acfb13c8
Revises: 8b6315ea26c6
Create Date: 2024-10-25 01:02:29.630967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68a2acfb13c8'
down_revision: Union[str, None] = '8b6315ea26c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_session', sa.Column('service_ids', sa.JSON(), nullable=False))
    op.drop_constraint('shared_session_ibfk_1', 'shared_session', type_='foreignkey')
    op.drop_column('shared_session', 'sniff_id')
    op.drop_column('shared_session', 'service_id')
    op.add_column('sniff', sa.Column('last_tested_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sniff', 'last_tested_time')
    op.add_column('shared_session', sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('shared_session', sa.Column('sniff_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('shared_session_ibfk_1', 'shared_session', 'sniff', ['sniff_id'], ['id'])
    op.drop_column('shared_session', 'service_ids')
    # ### end Alembic commands ###
