"""add expiration_time

Revision ID: 83f937286693
Revises: 68a2acfb13c8
Create Date: 2024-10-25 01:34:38.024757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f937286693'
down_revision: Union[str, None] = '68a2acfb13c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_session', sa.Column('expiration_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_session', 'expiration_time')
    # ### end Alembic commands ###
