"""add session_id to session

Revision ID: 8b6315ea26c6
Revises: 9a4ba9b480cf
Create Date: 2024-10-24 01:26:23.800756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b6315ea26c6'
down_revision: Union[str, None] = '9a4ba9b480cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_session', sa.Column('session_id', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_shared_session_session_id'), 'shared_session', ['session_id'], unique=False)
    op.drop_column('sniff', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sniff', sa.Column('url', mysql.TEXT(), nullable=False))
    op.drop_index(op.f('ix_shared_session_session_id'), table_name='shared_session')
    op.drop_column('shared_session', 'session_id')
    # ### end Alembic commands ###
