"""Add sniff table

Revision ID: cea8b6ec3422
Revises: f7a107475088
Create Date: 2024-10-24 00:43:28.608419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea8b6ec3422'
down_revision: Union[str, None] = 'f7a107475088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sniff_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sniff_data_client_id'), 'sniff_data', ['client_id'], unique=False)
    op.create_index(op.f('ix_sniff_data_id'), 'sniff_data', ['id'], unique=False)
    op.create_index(op.f('ix_sniff_data_service_id'), 'sniff_data', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sniff_data_service_id'), table_name='sniff_data')
    op.drop_index(op.f('ix_sniff_data_id'), table_name='sniff_data')
    op.drop_index(op.f('ix_sniff_data_client_id'), table_name='sniff_data')
    op.drop_table('sniff_data')
    # ### end Alembic commands ###
