"""make not nullable + shared session table

Revision ID: f66d6b47566a
Revises: fbbb6859d927
Create Date: 2024-10-24 01:07:38.855415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f66d6b47566a'
down_revision: Union[str, None] = 'fbbb6859d927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiration_duration_days', sa.Integer(), nullable=True),
    sa.Column('sniff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sniff_id'], ['sniff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_session_client_id'), 'shared_session', ['client_id'], unique=False)
    op.create_index(op.f('ix_shared_session_id'), 'shared_session', ['id'], unique=False)
    op.create_index(op.f('ix_shared_session_service_id'), 'shared_session', ['service_id'], unique=False)
    op.alter_column('sniff', 'client_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('sniff', 'service_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('sniff', 'url',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('sniff', 'headers',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=False)
    op.alter_column('sniff', 'cookies',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sniff', 'cookies',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('sniff', 'headers',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=True)
    op.alter_column('sniff', 'url',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('sniff', 'service_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('sniff', 'client_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_shared_session_service_id'), table_name='shared_session')
    op.drop_index(op.f('ix_shared_session_id'), table_name='shared_session')
    op.drop_index(op.f('ix_shared_session_client_id'), table_name='shared_session')
    op.drop_table('shared_session')
    # ### end Alembic commands ###
