"""rename table

Revision ID: fbbb6859d927
Revises: cea8b6ec3422
Create Date: 2024-10-24 01:05:53.835341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fbbb6859d927'
down_revision: Union[str, None] = 'cea8b6ec3422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sniff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sniff_client_id'), 'sniff', ['client_id'], unique=False)
    op.create_index(op.f('ix_sniff_id'), 'sniff', ['id'], unique=False)
    op.create_index(op.f('ix_sniff_service_id'), 'sniff', ['service_id'], unique=False)
    op.drop_index('ix_sniff_data_client_id', table_name='sniff_data')
    op.drop_index('ix_sniff_data_id', table_name='sniff_data')
    op.drop_index('ix_sniff_data_service_id', table_name='sniff_data')
    op.drop_table('sniff_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sniff_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('headers', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('cookies', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sniff_data_service_id', 'sniff_data', ['service_id'], unique=False)
    op.create_index('ix_sniff_data_id', 'sniff_data', ['id'], unique=False)
    op.create_index('ix_sniff_data_client_id', 'sniff_data', ['client_id'], unique=False)
    op.drop_index(op.f('ix_sniff_service_id'), table_name='sniff')
    op.drop_index(op.f('ix_sniff_id'), table_name='sniff')
    op.drop_index(op.f('ix_sniff_client_id'), table_name='sniff')
    op.drop_table('sniff')
    # ### end Alembic commands ###
