"""Add title to session

Revision ID: fc355c5eac7f
Revises: 83f937286693
Create Date: 2024-11-10 00:10:54.798335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc355c5eac7f'
down_revision: Union[str, None] = '83f937286693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_session', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_session', 'title')
    # ### end Alembic commands ###
