version: '3'

services:

  web-wings-core:
    image: web-wings:0.1
    container_name: web-wings
    ports:
      - "8000:8000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb-container
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
