COOKIE_EXPIRATION_SECONDS = 24 * 60 * 60

DATABASE_HOST = "127.0.0.1"
DATABASE_PORT = "3306"
DATABASE_USERNAME = "root"
DATABASE_PASSWORD = "my-secret-pw"
DATABASE_NAME = "db"
DATABASE_URL = \
    f"mysql+pymysql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"